In [10]:
import numpy as np
np.random.seed(2)
arr = np.random.randint(10, size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.nbytes)

[[8 8 6 2 8]
 [7 2 1 5 4]]
2
(2, 5)
10
int32
40


In [2]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(10,size=(10,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[-1,-2])

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]
 [9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]
 [5 1 9 3 4]
 [8 1 4 0 3]]
2
(10, 5)
50
int32
4
200
0


In [3]:
import numpy as np
np.random.seed(1)
arr = np.random.randint(10, size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[-1,-2])
print(arr[:2,:3])

[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
10
int32
4
40
6
[[5 8 9]
 [0 1 7]]


In [4]:
import numpy as np
np.random.seed()
arr = np.random.randint(10, size=10)
print(arr)
print(arr[3])
print(arr[-2])
print(arr[3:9:1])
print(arr[::-1])

[5 1 2 6 4 7 4 5 0 7]
6
0
[6 4 7 4 5 0]
[7 0 5 4 7 4 6 2 1 5]


In [6]:
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)
subarray = arr[1:4,:]
print(subarray)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
import numpy as np
arr = np.arange(1,13).reshape(3,4)
print(arr)
subarray = arr[1:4,:].copy()
print(subarray)
subarray[0,0] = 555
print(subarray)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[555   6   7   8]
 [  9  10  11  12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
