In [3]:
import numpy as np
x=np.random.randint(1,100,10)
print(x)
y= np.sort(x)
print(y)
x.sort()
print(x)

[75 29 70 85 72 92 60 52 53 29]
[29 29 52 53 60 70 72 75 85 92]
[29 29 52 53 60 70 72 75 85 92]


In [4]:
import numpy as np
x=np.array([45,33,56,11,23,16,17])
print(x)
i=np.argsort(x)
y=x[i]
print(np.sort(x))
print(y)

[45 33 56 11 23 16 17]
[11 16 17 23 33 45 56]
[11 16 17 23 33 45 56]


In [7]:
import numpy as np
x=np.random.randint(1,50,(4,6))
print(x)
r=np.sort(x,axis=1)
c=np.sort(x,axis=0)
print(r)
print(c)

[[42 28 10 21 12  2]
 [32 35 15 12 33 36]
 [40 26  2 16 18  1]
 [ 8 31 25 15 26 16]]
[[ 2 10 12 21 28 42]
 [12 15 32 33 35 36]
 [ 1  2 16 18 26 40]
 [ 8 15 16 25 26 31]]
[[ 8 26  2 12 12  1]
 [32 28 10 15 18  2]
 [40 31 15 16 26 16]
 [42 35 25 21 33 36]]


In [1]:
import numpy as np

name = ["alice", "bob", "cathy", "jaan"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 29.5]

dtype = np.dtype({
    "names": ["name", "age", "weight"],
    "formats": ["U10", "i4", "f8"],
})

data = np.zeros(4, dtype=dtype)

print("Structured array using a compound data type")

data["name"] = name
data["age"] = age
data["weight"] = weight

print("Filled structured array")
print(data)

print("All names")
print(data["name"])

print("First row data")
print(data[0])

print("Name from the last row")
print(data[-1]["name"])

print("Names where age is under 30")
print(data[data["age"] < 30]["name"])

Structured array using a compound data type
Filled structured array
[('alice', 25, 55. ) ('bob', 45, 85.5) ('cathy', 37, 68. )
 ('jaan', 19, 29.5)]
All names
['alice' 'bob' 'cathy' 'jaan']
First row data
('alice', 25, 55.0)
Name from the last row
jaan
Names where age is under 30
['alice' 'jaan']


In [ ]:
data_rec =data.view(np.recarray)
print(data_rec.age)
%