In [2]:
def add(a,b):
    return a+b
add?
add??

Signature: add(a, b)
Docstring: <no docstring>
Source:   
def add(a,b):
    return a+b
File:      c:\users\user\appdata\local\temp\ipykernel_15180\1298367435.py
Type:      function

In [8]:
%timeit [n**2 for n in range(10000)]
def squares_loop():
    result=[]
    for n in range(10000):
        result.append(n**2)
    return result
%timeit squares_loop()

470 μs ± 13.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
591 μs ± 22.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%history -n 1-5

   1:
def add(a, b):
    return a + b
add?
add??
   2:
def add(a,b):
    return a+b
add?
add??
   3:
%timeit [n**2 for n in range(10000)]
def squares_loop():
    result = []
    for n in range(10000):
        result.append(n**2)
    return result

%timeit squares_loop()
   4:
def divide_by_zero():
    x = 10
    return x / 0

%xmode Verbose
divide_by_zero()
   5:
def divide_by_zero():
    x = 10
    return x/0

%xmode Verbose
divide_by_zero()


In [14]:
def divide_by_zero():
    x = 10
    return x / 0

%xmode Verbose
divide_by_zero()


Exception reporting mode: Verbose


ZeroDivisionError: division by zero

In [15]:
%debug


> c:\users\user\appdata\local\temp\ipykernel_15180\367195916.py(3)divide_by_zero()



ipdb>  where


    [... skipping 1 hidden frame(s)]
  c:\users\user\appdata\local\temp\ipykernel_15180\367195916.py(6)<module>()
> c:\users\user\appdata\local\temp\ipykernel_15180\367195916.py(3)divide_by_zero()



ipdb>  locals()


{'x': 10}


ipdb>  quit


In [18]:
%%writefile myscript.py
def greet(name):
    return f"Hello, {name}!"

Writing myscript.py


In [19]:
%run myscript.py
greet("Data Science")

'Hello, Data Science!'

In [21]:
%lsmagic
def sum_squares():
    return sum(n**2 for n in range(100000))
%prun sum_squares()

         100017 function calls in 0.033 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.020    0.020    0.024    0.024 281224934.py:3(sum_squares)
   100001    0.011    0.000    0.011    0.000 281224934.py:4(<genexpr>)
        1    0.002    0.002    0.004    0.004 {built-in method builtins.sum}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.024    0.024 {built-in method builtins.exec}
        3    0.000    0.000    0.000    0.000 enum.py:1589(_get_value)
        1    0.000    0.000    0.000    0.000 enum.py:1596(__or__)
        1    0.000    0.000    0.000    0.000 enum.py:695(__call__)
        5    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        1    0.000    0.000    0.024    0.024 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 enum.py:1156(__new__)

In [22]:
import numpy as np
arr = np.arange(1, 21)
print(arr)
print(arr.ndim)  
print(arr.shape) 
print(arr.size)   
print(arr.dtype) 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(20,)
20
int64


In [23]:
np.random.seed(0)
arr = np.random.randint(0, 51, size=(4,5))
print(arr)
print(arr.itemsize)  
print(arr.nbytes)    

[[44 47  0  3  3]
 [39  9 19 21 50]
 [36 23  6 24 24]
 [12  1 38 39 23]]
4
80


In [24]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr[1, 2])  
print(arr[-1])    
print(arr[:, -1]) 

7
[ 9 10 11 12]
[ 4  8 12]


In [25]:
print(arr[:2, :2])   
print(arr[:, ::2])   
print(arr[:, ::-1])  

[[1 2]
 [5 6]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [26]:
original = np.arange(1, 21).reshape(5,4)
view = original[:3,:]
view[0, 0] =99
print(original)  
original = np.arange(1, 21).reshape(5, 4)
copy = original[:3, :].copy()
copy[0, 0] = 99
print(original) 

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [27]:
x = np.arange(1,13)
matrix = x.reshape(3,4)
column1 = x.reshape((12,1))
column2 = x[:, np.newaxis]
print(matrix)
print(column1)
print(np.array_equal(column1,column2))  

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
True


In [28]:
a = np.random.randint(0, 10, size=(2,3))
b = np.random.randint(0,10, size=(2,3))
vertical1 = np.vstack((a, b))
vertical2 = np.concatenate((a, b), axis=0)
print(np.array_equal(vertical1, vertical2))  
horizontal1 = np.hstack((a, b))
horizontal2 = np.concatenate((a, b), axis=1)
print(np.array_equal(horizontal1, horizontal2))  

True
True


In [29]:
x = np.arange(15)
parts = np.split(x,3)
for part in parts:
    print(part)


[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]


In [32]:
arr = np.arange(24).reshape(6,4)
left, right = np.hsplit(arr,2)
top, bottom = np.vsplit(arr,2)
print(left)
print(right)
print(top)
print(bottom)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [31]:
x =np.random.randint(0,100,size=10)
sorted_copy =np.sort(x)
print("Original unchanged:", x)
print("Sorted copy:",sorted_copy)
x.sort()
print("Original changed:", x)

Original unchanged: [82 99 88 49 29 19 19 14 39 32]
Sorted copy: [14 19 19 29 32 39 49 82 88 99]
Original changed: [14 19 19 29 32 39 49 82 88 99]


In [33]:
x = np.random.randint(0,100,size=10)
i =np.argsort(x)
print(x[i])
print(np.sort(x))

[ 9 23 31 32 35 55 57 65 74 75]
[ 9 23 31 32 35 55 57 65 74 75]


In [34]:
student_names = np.array(["Asha", "Ben","Chen","Diya"])
scores = np.array([88, 72, 95, 81])
order = np.argsort(scores)
print(student_names[order])
print(scores[order])

['Ben' 'Diya' 'Asha' 'Chen']
[72 81 88 95]


In [35]:
student_names =np.array(["Asha", "Ben","Chen","Diya"])
scores =np.array([88, 72, 95, 81])
order = np.argsort(scores)
print(student_names[order])
print(scores[order])

['Ben' 'Diya' 'Asha' 'Chen']
[72 81 88 95]


In [36]:
book_dtype = [ ("title", "U30"), ("author", "U20"), ("price", "f8")]
books = np.array([ ("The Hobbit", "Tolkien", 12.99),("Matilda", "Dahl", 9.50), ("Dune", "Herbert", 15.00), ("Coraline", "Gaiman", 8.75)], dtype=book_dtype)

print(books)

[('The Hobbit', 'Tolkien', 12.99) ('Matilda', 'Dahl',  9.5 )
 ('Dune', 'Herbert', 15.  ) ('Coraline', 'Gaiman',  8.75)]


In [37]:
print(books["title"]) 
print(books[1])        
print(books[books["price"] <12])

['The Hobbit' 'Matilda' 'Dune' 'Coraline']
('Matilda', 'Dahl', 9.5)
[('Matilda', 'Dahl', 9.5 ) ('Coraline', 'Gaiman', 8.75)]


In [38]:
student_dtype = [ ("roll_no", "i4"),("name", "U20"), ("marks", "f8")]
students = np.array([ (1, "Asha", 87.5), (2, "Ben", 92.0),(3, "Chen", 78.0),(4, "Diya", 95.5),(5, "Eli", 84.0)], dtype=student_dtype)
sorted_students = students[np.argsort(students["marks"])[::-1]]
print(sorted_students)

[(4, 'Diya', 95.5) (2, 'Ben', 92. ) (1, 'Asha', 87.5) (5, 'Eli', 84. )
 (3, 'Chen', 78. )]
